[theme]
backgroundColor="#ececde"
secondaryBackgroundColor="#dddde0"
textColor="#2f2b2b"

GOOGLEAI_API_KEY = 'AIzaSyAqkVyZJY6ON-LWx6YbHMgWbwOOPjYiOoo'

[global]
hideStreamlitFooter = true
layout = "wide"
